spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://152.136.176.18:3306/product?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      url: jdbc:mysql://127.0.0.1:3306/demo1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root
server:
  port: 8091

logging:
  level:
    com.yc.base.dao : debug
#pagehelper:
mybatis:
  mapper-locations: com.wm.project.project.dao/*.xml
#  helperDialect: mysql

file:
  #客户端请求头像的虚拟路径。（此处可以将“头像”改成任意需要直接获取的资源）
  filePath: /file/**
  #上传文件路径
  uploadFolder:   C:\\Users\DELL\Desktop\校园\goods_images\

#  E://file/

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

